# Generated by Django 5.2.4 on 2025-08-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la bodega')),
                ('pais', models.CharField(max_length=50, verbose_name='País de origen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del vino')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (Malbec, Cabernet...)')),
                ('año', models.PositiveIntegerField(verbose_name='Año de cosecha')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinos', to='mi_primer_app.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='mi_primer_app.vino')),
            ],
        ),
    ]
