# Generated by Django 5.2.4 on 2025-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='vino',
            name='año',
        ),
        migrations.RemoveField(
            model_name='vino',
            name='tipo',
        ),
        migrations.AddField(
            model_name='bodega',
            name='direccion',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
        migrations.AddField(
            model_name='bodega',
            name='historia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bodegas/'),
        ),
        migrations.AddField(
            model_name='vino',
            name='cepa',
            field=models.CharField(default='Malbec', max_length=50),
        ),
        migrations.AddField(
            model_name='vino',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vinos/'),
        ),
        migrations.AddField(
            model_name='vino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vino',
            name='terroir',
            field=models.CharField(default='Mendoza', max_length=50),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vino',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
