# Generated by Django 5.2.4 on 2025-08-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_remove_bodega_descripcion_remove_vino_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='estilo_visual',
            field=models.CharField(blank=True, help_text='Ej: minimalista, rústico, moderno', max_length=100),
        ),
        migrations.AddField(
            model_name='bodega',
            name='lema',
            field=models.CharField(blank=True, help_text='Frase que sintetiza la filosofía de la bodega', max_length=150),
        ),
        migrations.AddField(
            model_name='vino',
            name='descripcion_sensorial',
            field=models.TextField(blank=True, help_text='Notas de cata, aromas, boca, final'),
        ),
        migrations.AddField(
            model_name='vino',
            name='destacado',
            field=models.BooleanField(default=False, help_text='¿Mostrar como sugerido en la bodega?'),
        ),
        migrations.AddField(
            model_name='vino',
            name='maridaje',
            field=models.CharField(blank=True, help_text='Ej: carnes rojas, quesos curados', max_length=150),
        ),
    ]
