# Generated by Django 5.2.4 on 2025-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='fecha_publicacion',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='titulo',
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default='Sin subtítulo', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
