# Generated by Django 5.2.4 on 2025-08-22 12:59

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_autor_page_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido enriquecido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default='Sin subtítulo', max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='Sin título', max_length=200, verbose_name='Título'),
        ),
    ]
