# Generated by Django 5.2.4 on 2025-08-22 16:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_alter_page_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('varietal', models.CharField(max_length=100)),
                ('añada', models.DateField()),
                ('notas', ckeditor.fields.RichTextField()),
                ('maridaje', models.TextField()),
                ('imagen', models.ImageField(upload_to='vinos/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
