# Generated by Django 5.2.4 on 2025-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_vino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vinos/'),
        ),
    ]
