# Generated by Django 5.2.4 on 2025-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_vino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
