# Generated by Django 5.2.4 on 2025-08-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='descripcion_sensorial',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
